### ISSUE TITLE
Not able to authenticate with github, 

### ISSUE THREAD

**Issue by PrafullSaxena** [Mustafiz04/CodeSyncer#4]
**Description**
While Clicking on the authenticate on Github button it takes the OAuth URL to Github however it's not authenticating.

**Steps to reproduce the behavior:**
1. Click on Extension
2. Click on 'Authenticate with GitHub
3. See error

It should let me authenticate with the GitHub Creds. 

**Screenshots**
![Screenshot 2023-08-29 at 1 13 32 PM](https://github.com/Mustafiz04/CodeSyncer/assets/28269065/4d3bbf2a-999b-4197-afe4-0120293a3129)

![Screenshot 2023-08-29 at 1 11 22 PM](https://github.com/Mustafiz04/CodeSyncer/assets/28269065/139714ae-e484-4015-a6ea-3c5d0d3a8ec5)

**Additional context**
Please let me know if there is any other way of authenticating.

**Comment by Mustafiz04** [comment]
Hi @PrafullSaxena 
Thank you for reporting this issue.
Let me see and fix the issue.

**Comment by Mustafiz04** [comment]
I fixed this issue and published the new package with `v1.1.2`
You can try once it is published after verification.

Thank you so much for reporting.
The best part is that you can also contribute to this repo and make it better if you want to.

**Comment by Mustafiz04** [comment]
Hi @PrafullSaxena 
The issue has been fixed. Can you please check and let me know?

**Comment by PrafullSaxena** [comment]
It looks good now, Thanks @Mustafiz04 for the quick response.
